export const USER_DETAILS = 'USER_DETAILS';
export const USER_DETAILS_PROCESSING = 'USER_DETAILS_PROCESSING';
export const USER_DETAILS_FAILED = 'USER_DETAILS_FAILED';
export const CREDITIONALS = 'CREDITIONALS';
export const CREDITIONALS_PROCESSING = 'CREDITIONALS_PROCESSING';
export const CREDITIONALS_FAILED = 'CREDITIONALS_FAILED';
