/* tslint:disable */
/* eslint-disable */
/**
 * CodeCharacter API
 * Specification of the CodeCharacter API
 *
 * The version of the OpenAPI document: 2022.0.1
 * Contact: delta@nitt.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface GetGameLogsByGameIdRequest {
  gameId: string;
}

/**
 * GameApi - interface
 *
 * @export
 * @interface GameApiInterface
 */
export interface GameApiInterface {
  /**
   * Get game logs by game ID
   * @summary Get game logs by game ID
   * @param {string} gameId UUID of the game
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GameApiInterface
   */
  getGameLogsByGameIdRaw(
    requestParameters: GetGameLogsByGameIdRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<string>>;

  /**
   * Get game logs by game ID
   * Get game logs by game ID
   */
  getGameLogsByGameId(
    gameId: string,
    initOverrides?: RequestInit,
  ): Promise<string>;
}

/**
 *
 */
export class GameApi extends runtime.BaseAPI implements GameApiInterface {
  /**
   * Get game logs by game ID
   * Get game logs by game ID
   */
  async getGameLogsByGameIdRaw(
    requestParameters: GetGameLogsByGameIdRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<string>> {
    if (
      requestParameters.gameId === null ||
      requestParameters.gameId === undefined
    ) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter requestParameters.gameId was null or undefined when calling getGameLogsByGameId.',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('http-bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/games/{gameId}/logs`.replace(
          `{${'gameId'}}`,
          encodeURIComponent(String(requestParameters.gameId)),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.TextApiResponse(response) as any;
  }

  /**
   * Get game logs by game ID
   * Get game logs by game ID
   */
  async getGameLogsByGameId(
    gameId: string,
    initOverrides?: RequestInit,
  ): Promise<string> {
    const response = await this.getGameLogsByGameIdRaw(
      { gameId: gameId },
      initOverrides,
    );
    return await response.value();
  }
}
