name: Docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Attempt to use cached dependencies
        uses: actions/cache@v2
        id: cache-yarn
        with:
          path: './node_modules'
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock', 'patches/**') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-
      - name: Install dependencies
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: yarn install
      - name: Copy config
        run: |
          cp ./src/config/config.example.ts ./src/config/config.ts
          sed -i 's/http:\/\/localhost:8080/https:\/\/stoplight.io\/mocks\/rinish-api-testbed\/codecharacter\/14036190/' ./src/config/config.ts
      - name: Run build
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Create storybook
        run: yarn storybook:build
      - name: Prepare deployment
        run: |
          mv dist docs/deployment
          mv coverage/lcov-report docs/coverage
          mv storybook-static docs/storybook
      - name: Push coverage report
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git branch -D gh-pages || echo "Branch does not exist"
          git checkout --orphan gh-pages
          git rm --cached $(git ls-files)
          git add docs/*
          git commit -m "Update docs"
          git push -f origin gh-pages
